FROM python:3.12-slim

WORKDIR /app

ENV PYTHONPATH="/app:/app/django_project"

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client \
    libpango-1.0-0 libpangoft2-1.0-0 libpangocairo-1.0-0 libcairo2 libglib2.0-0 libgdk-pixbuf-2.0-0 libffi-dev shared-mime-info \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x entrypoint-django.sh

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint-django.sh"]
