services:
  frontend:
    ports:
      - "80:80"  # Esto permite que entres por localhost en Windows
    build:
      context: ./sys-plan
      args:
        VITE_API_URL: "http://localhost:8001"
    environment:
      VITE_API_URL: "http://localhost:8001"

  django-admin:
    ports:
      - "8000:8000" # Para entrar al admin de Django en local

  fastapi-api:
    ports:
      - "8001:8001" # Para probar el API en local
    environment:
      ALLOWED_ORIGINS: "http://localhost,http://127.0.0.1,http://localhost:80,http://localhost:5173"
      APP_ENV: local
      ENABLE_DOCS: "true"

networks:
  dokploy-network:
    external: false # En Windows, Docker creará la red automáticamente