# Generated by Django 5.2.14 on 2026-06-01 02:07

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='CoreAcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField()),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'plan_app_academicperiod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreEvaluationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('competence', models.CharField(blank=True, max_length=255)),
                ('strategy', models.CharField(blank=True, max_length=255)),
                ('instrument', models.CharField(blank=True, max_length=255)),
                ('evidence', models.CharField(blank=True, max_length=255)),
                ('feedback_method', models.CharField(blank=True, max_length=255)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('due_week', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_app_evaluationplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreLessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'plan_app_lessonplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('previous_competencies', models.TextField(blank=True, null=True)),
                ('generic_competencies', models.TextField(blank=True, null=True)),
                ('teaching_strategies', models.TextField(blank=True, null=True)),
                ('eval_diagnostica', models.TextField(blank=True, null=True)),
                ('eval_formativa', models.TextField(blank=True, null=True)),
                ('eval_sumativa', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_app_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreSubjectUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('unit_title', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('performance_criteria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_app_subjectunit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreSyllabusVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan_app_syllabusversion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'plan_app_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreWeeklyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('content_description', models.TextField(blank=True)),
                ('teaching_strategy', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('bibliography', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'plan_app_weeklycontent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del proveedor (ej. OpenAI, DeepSeek)', max_length=100, unique=True)),
                ('provider_type', models.CharField(default='openai-compatible', max_length=50)),
                ('base_url', models.CharField(blank=True, help_text='URL base de la API, útil para compatibles con OpenAI', max_length=255, null=True)),
                ('api_key_encrypted', models.TextField(help_text='Clave de API cifrada')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_app_provider',
            },
        ),
        migrations.CreateModel(
            name='AgentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('system_prompt', models.TextField(help_text='Instrucciones base (Directrices) que el agente seguirá para evaluar planes.')),
                ('json_schema_output', models.JSONField(blank=True, help_text='Formato esperado de salida (schema JSON)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_app.aiprovider')),
            ],
            options={
                'db_table': 'ai_app_agent_template',
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('result_data', models.JSONField(blank=True, help_text='Respuesta estructurada del LLM', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_app.agenttemplate')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluations', to='ai_app.corelessonplan')),
            ],
            options={
                'db_table': 'ai_app_evaluation_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='Vector de embeddings del fragmento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_app.coresyllabusversion')),
            ],
            options={
                'db_table': 'ai_app_syllabus_chunk',
                'ordering': ['syllabus', 'chunk_index'],
            },
        ),
    ]
