# Generated by Django 5.2.14 on 2026-06-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Modelo para embeddings', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='llm_model',
            field=models.CharField(blank=True, help_text='Modelo LLM', max_length=255, null=True),
        ),
    ]
