# Generated by Django 5.2.14 on 2026-06-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_aiprovider_embedding_model_aiprovider_llm_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Acción realizada (ej. Prueba de Conexión, Vectorización)', max_length=150)),
                ('status', models.CharField(help_text='Estado (ej. success, failed, started)', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Detalles o traza del error', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_app_ailog',
                'ordering': ['-created_at'],
            },
        ),
    ]
