# Generated by Django 5.2.14 on 2026-06-04 14:37

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0003_ailog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabuschunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(help_text='Vector de embeddings del fragmento'),
        ),
    ]
