# Generated by Django 5.2.14 on 2026-06-04 17:06

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0004_alter_syllabuschunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(help_text='Vector de embeddings del fragmento del plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_app.corelessonplan')),
            ],
            options={
                'db_table': 'ai_app_lessonplan_chunk',
                'ordering': ['lesson_plan', 'chunk_index'],
            },
        ),
    ]
