# Generated by Django 5.2.14 on 2026-06-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0005_lessonplanchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttemplate',
            name='agent_type',
            field=models.CharField(default='chat', help_text='evaluator o chat', max_length=50),
        ),
        migrations.AddField(
            model_name='agenttemplate',
            name='enabled_tools',
            field=models.JSONField(blank=True, default=list, help_text='Lista de nombres de herramientas habilitadas'),
        ),
    ]
