# Generated by Django 5.2.15 on 2026-06-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0007_chatsession_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan_app_career',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('subject_codes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan_app_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan_app_faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('lesson_plan_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plan_app_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField(blank=True, help_text='Facultad a la que aplica', null=True)),
                ('department_id', models.IntegerField(blank=True, help_text='Departamento al que aplica', null=True)),
                ('career_id', models.IntegerField(blank=True, help_text='Carrera a la que aplica', null=True)),
                ('subject_code', models.CharField(blank=True, help_text='Código de asignatura específica', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ai_app.agenttemplate')),
            ],
            options={
                'db_table': 'ai_app_agent_assignment',
                'ordering': ['-created_at'],
            },
        ),
    ]
