# Generated by Django 5.2.15 on 2026-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0008_corecareer_coredepartment_corefaculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentassignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la asignación está activa'),
        ),
    ]
