# Generated by Django 5.2.15 on 2026-06-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0009_agentassignment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentassignment',
            name='section',
            field=models.CharField(blank=True, help_text='Sección específica de la asignatura', max_length=50, null=True),
        ),
    ]
