# Generated by Django 5.2.15 on 2026-06-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0010_agentassignment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='completion_tokens',
            field=models.IntegerField(default=0, help_text='Tokens de salida de la respuesta'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='prompt_tokens',
            field=models.IntegerField(default=0, help_text='Tokens de entrada del prompt'),
        ),
    ]
