# Generated by Django 5.2.15 on 2026-06-11 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0011_evaluationresult_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='context_limit',
            field=models.IntegerField(default=2000, help_text='Límite de contexto en caracteres (Min 1000, Max 10000)', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
