# Generated by Django 5.2.15 on 2026-06-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0012_aiprovider_context_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailog',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ailog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ailog',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ailog',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
