# Generated by Django 5.2.15 on 2026-06-19 03:33

import django.contrib.postgres.search
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0013_ailog_completion_tokens_ailog_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUserAcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.TextField(blank=True, null=True)),
                ('section', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan_app_user_academic_period',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='lessonplanchunk',
            name='contextualized_content',
            field=models.TextField(blank=True, help_text='Texto contextualizado por LLM (contexto + chunk original). Persiste para re-indexación sin costo de LLM.', null=True),
        ),
        migrations.AddField(
            model_name='lessonplanchunk',
            name='embedding_model',
            field=models.CharField(blank=True, help_text="Identificador del modelo de embeddings usado (ej. 'text-embedding-3-small').", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lessonplanchunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Vector BM25 para búsqueda de texto completo en PostgreSQL.', null=True),
        ),
        migrations.AddField(
            model_name='syllabuschunk',
            name='contextualized_content',
            field=models.TextField(blank=True, help_text='Texto contextualizado por LLM (contexto + chunk original). Persiste para re-indexación sin costo de LLM.', null=True),
        ),
        migrations.AddField(
            model_name='syllabuschunk',
            name='embedding_model',
            field=models.CharField(blank=True, help_text="Identificador del modelo de embeddings usado (ej. 'text-embedding-3-small').", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='syllabuschunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Vector BM25 para búsqueda de texto completo en PostgreSQL.', null=True),
        ),
        migrations.AddIndex(
            model_name='syllabuschunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='syllabus_chunk_search_gin'),
        ),
        migrations.AddIndex(
            model_name='lessonplanchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='lesson_plan_chunk_search_gin'),
        ),
    ]
