# Generated by Django 5.2.15 on 2026-06-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0014_coreuseracademicperiod_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lessonplanchunk',
            name='lesson_plan_chunk_search_gin',
        ),
        migrations.RemoveIndex(
            model_name='syllabuschunk',
            name='syllabus_chunk_search_gin',
        ),
        migrations.AddField(
            model_name='ailog',
            name='current_document_name',
            field=models.CharField(blank=True, help_text='Nombre del documento que se está analizando', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ailog',
            name='processed_percent',
            field=models.FloatField(default=0.0, help_text='Porcentaje de procesamiento actual'),
        ),
    ]
