# Generated by Django 5.2.15 on 2026-06-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0015_remove_lessonplanchunk_lesson_plan_chunk_search_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='disable_thinking',
            field=models.BooleanField(default=True, help_text='Si está activo, instruye al modelo a omitir el razonamiento extendido (thinking). Recomendado siempre para vectorización de documentos.'),
        ),
    ]
