# Generated by Django 5.0.4 on 2026-05-05 03:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FACULTY', 'Facultad'), ('ACADEMIC_PROGRAM', 'Programa Academico'), ('MODALITY', 'Modalidad')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
                'db_table': 'plan_app_catalog',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_hours', models.IntegerField()),
                ('hiv_hours', models.IntegerField()),
                ('hde_hours', models.IntegerField()),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parametro Academico',
                'verbose_name_plural': 'Parametros Academicos',
                'db_table': 'plan_app_parameter',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('ADMIN_GESTION', 'Administrador de Gestion'), ('COORDINADOR', 'Coordinador'), ('DOCENTE', 'Docente')], default='DOCENTE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'plan_app_user',
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_REVIEW', 'En Revision'), ('OBSERVED', 'Observado'), ('APPROVED', 'Aprobado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_plans', to=settings.AUTH_USER_MODEL)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_plans', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='plan_app.catalog')),
            ],
            options={
                'verbose_name': 'Plan de Clase',
                'verbose_name_plural': 'Planes de Clase',
                'db_table': 'plan_app_lessonplan',
            },
        ),
        migrations.CreateModel(
            name='EvaluationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('competence', models.CharField(blank=True, max_length=255)),
                ('strategy', models.CharField(blank=True, max_length=255)),
                ('instrument', models.CharField(blank=True, max_length=255)),
                ('evidence', models.CharField(blank=True, max_length=255)),
                ('feedback_method', models.CharField(blank=True, max_length=255)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('due_week', models.IntegerField(blank=True, null=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_plans', to='plan_app.lessonplan')),
            ],
            options={
                'verbose_name': 'Plan de Evaluacion',
                'verbose_name_plural': 'Planes de Evaluacion',
                'db_table': 'plan_app_evaluationplan',
            },
        ),
        migrations.CreateModel(
            name='WeeklyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('content_description', models.TextField(blank=True)),
                ('teaching_strategy', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('bibliography', models.TextField(blank=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_contents', to='plan_app.lessonplan')),
            ],
            options={
                'verbose_name': 'Contenido Semanal',
                'verbose_name_plural': 'Contenidos Semanales',
                'db_table': 'plan_app_weeklycontent',
            },
        ),
        migrations.AddConstraint(
            model_name='weeklycontent',
            constraint=models.CheckConstraint(check=models.Q(('week_number__gte', 1), ('week_number__lte', 12)), name='check_week_number_range'),
        ),
    ]
