# Generated by Django 5.0.4 on 2026-05-22 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0003_user_deactivated_at_user_deactivation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('document_code', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(default='PREGRADO', max_length=50)),
                ('identification_date', models.DateField(blank=True, null=True)),
                ('syllabus_version_year', models.CharField(blank=True, max_length=10, null=True)),
                ('academic_credits', models.IntegerField(default=0)),
                ('had_hours', models.IntegerField(default=0)),
                ('hde_hours', models.IntegerField(default=0)),
                ('hts_hours', models.IntegerField(default=0)),
                ('academic_period', models.IntegerField(blank=True, null=True)),
                ('prerequisite', models.TextField(blank=True, null=True)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('previous_competencies', models.TextField(blank=True, null=True)),
                ('generic_competencies', models.TextField(blank=True, null=True)),
                ('relation_other_subjects', models.TextField(blank=True, null=True)),
                ('teaching_strategies', models.TextField(blank=True, null=True)),
                ('eval_diagnostica', models.TextField(blank=True, null=True)),
                ('eval_formativa', models.TextField(blank=True, null=True)),
                ('eval_sumativa', models.TextField(blank=True, null=True)),
                ('bibliographic_references', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'plan_app_subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondences', to='plan_app.subject')),
            ],
            options={
                'verbose_name': 'Correspondencia de Materia',
                'verbose_name_plural': 'Correspondencias de Materias',
                'db_table': 'plan_app_subjectcorrespondence',
            },
        ),
        migrations.CreateModel(
            name='SubjectUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('unit_title', models.CharField(blank=True, max_length=255, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('performance_criteria', models.TextField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='plan_app.subject')),
            ],
            options={
                'verbose_name': 'Unidad de Aprendizaje',
                'verbose_name_plural': 'Unidades de Aprendizaje',
                'db_table': 'plan_app_subjectunit',
            },
        ),
        migrations.CreateModel(
            name='SyllabusVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='plan_app.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_syllabuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version de Programa Sinoptico',
                'verbose_name_plural': 'Versiones de Programas Sinopticos',
                'db_table': 'plan_app_syllabusversion',
            },
        ),
    ]
