# Generated by Django 5.0.4 on 2026-05-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0005_user_academic_period_user_first_name_user_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_period',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
