# Generated by Django 5.0.4 on 2026-05-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0006_alter_user_academic_period_alter_user_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Periodo')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Vigente')),
                ('type', models.CharField(choices=[('NORMAL', 'Periodo Normal'), ('INTENSIVO', 'Periodo Intensivo')], default='NORMAL', max_length=20, verbose_name='Tipo de Periodo')),
            ],
            options={
                'verbose_name': 'Periodo Academico',
                'verbose_name_plural': 'Periodos Academicos',
                'db_table': 'plan_app_academicperiod',
            },
        ),
    ]
