# Generated by Django 5.0.4 on 2026-05-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0007_academicperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_period_ref',
            field=models.ForeignKey(blank=True, db_column='academic_period_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='plan_app.academicperiod'),
        ),
    ]
