# Generated by Django 5.0.4 on 2026-05-24 23:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0008_user_academic_period_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='academic_period',
        ),
        migrations.RemoveField(
            model_name='user',
            name='academic_period_ref',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subject_code',
        ),
        migrations.CreateModel(
            name='UserAcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.TextField(blank=True, null=True)),
                ('section', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en este periodo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de asignación')),
                ('creation_method', models.CharField(choices=[('BULK', 'Carga por Lote'), ('MANUAL', 'Individual')], default='MANUAL', max_length=20, verbose_name='Método de Creación')),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='plan_app.academicperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_period_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación Usuario - Periodo Académico',
                'verbose_name_plural': 'Relaciones Usuario - Periodos Académicos',
                'db_table': 'plan_app_user_academic_period',
                'unique_together': {('user', 'academic_period')},
            },
        ),
    ]
