# Generated by Django 5.0.4 on 2026-05-26 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0009_remove_user_academic_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='academic_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='plan_app.academicperiod'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='section',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
