# Generated by Django 5.0.4 on 2026-05-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0010_lessonplan_academic_period_lessonplan_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_REVIEW', 'En Revision'), ('OBSERVED', 'Observado'), ('APPROVED', 'Aprobado'), ('PRUEBA', 'Prueba')], default='DRAFT', max_length=20),
        ),
    ]
