# Generated by Django 5.0.4 on 2026-05-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0011_alter_lessonplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Facultad')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código de Facultad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vigente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'plan_app_faculty',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Departamento')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código de Departamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vigente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='plan_app.faculty', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'plan_app_department',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Carrera')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código de Carrera')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vigente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='plan_app.faculty', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'plan_app_career',
            },
        ),
    ]
