# Generated by Django 5.0.4 on 2026-05-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0012_faculty_department_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='subject_codes',
            field=models.TextField(blank=True, help_text='Separados por coma', null=True, verbose_name='Códigos de Cursos Relacionados'),
        ),
    ]
