# Generated by Django 5.0.4 on 2026-05-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0014_permission_role_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('component_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'db_table': 'plan_app_widget',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='plan_app.role')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='plan_app.widget')),
            ],
            options={
                'verbose_name': 'Widget por Rol',
                'verbose_name_plural': 'Widgets por Rol',
                'db_table': 'plan_app_dashboard_widget_role',
                'ordering': ['order'],
                'unique_together': {('role', 'widget')},
            },
        ),
    ]
