# Generated by Django 5.0.4 on 2026-05-28 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0015_widget_dashboardwidgetrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='plan_app.department', verbose_name='Departamento Asignado'),
        ),
    ]
