# Generated by Django 5.0.4 on 2026-05-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0016_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, db_table='plan_app_user_departments', related_name='users', to='plan_app.department', verbose_name='Departamentos Asignados'),
        ),
    ]
