# Generated by Django 5.0.4 on 2026-06-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0018_evaluationplan_evaluation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationplan',
            name='competence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationplan',
            name='evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationplan',
            name='feedback_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationplan',
            name='instrument',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationplan',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
