# Generated by Django 5.0.4 on 2026-06-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0019_alter_evaluationplan_competence_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklycontent',
            name='check_week_number_range',
        ),
        migrations.AddConstraint(
            model_name='weeklycontent',
            constraint=models.CheckConstraint(check=models.Q(('week_number__gte', 1), ('week_number__lte', 18)), name='check_week_number_range'),
        ),
    ]
