# Generated by Django 5.0.4 on 2026-06-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0020_remove_weeklycontent_check_week_number_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationplan',
            name='due_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evaluationplan',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
