# Generated by Django 5.0.4 on 2026-06-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0021_evaluationplan_due_date_evaluationplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
