# Generated by Django 5.0.4 on 2026-06-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0023_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectunit',
            name='unit_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
