# Generated by Django 5.0.4 on 2026-06-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0024_alter_subjectunit_unit_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='objectives',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='strategies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
