# Generated by Django 5.0.4 on 2026-06-22 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0025_lessonplan_objectives_lessonplan_strategies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICopilotUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('attempts_used', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_copilot_usages', to='plan_app.academicperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_copilot_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Copiloto de IA',
                'verbose_name_plural': 'Usos de Copiloto de IA',
                'db_table': 'plan_app_ai_copilot_usage',
                'unique_together': {('user', 'academic_period', 'subject_code', 'section')},
            },
        ),
    ]
