server {
    listen 80;

    # Frontend de React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para el Backend (FastAPI)
    location /api/ {
        # La barra al final "/" es crucial. 
        # Si la petición es /api/token, Nginx envía /token a FastAPI.
        proxy_pass http://fastapi-api:8001/;
        
        # Pasar los headers reales para que FastAPI sepa quién hace la petición
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
